# -*- coding: utf-8 -*-
"""
Expand "Tentang" sections in each tool HTML file to 200-300+ words for SEO.
"""

import re, os, sys

sys.stdout.reconfigure(encoding='utf-8')

DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

EXPANDED = {
    "Konverter Bilangan": (
        "Konverter bilangan online untuk mengkonversi angka antar empat sistem bilangan sekaligus: desimal (basis 10), biner (basis 2), oktal (basis 8), dan heksadesimal (basis 16). Alat ini sangat berguna bagi mahasiswa teknik informatika, programmer, network engineer, dan siapa pun yang sedang mempelajari sistem bilangan komputer. Cukup masukkan angka pada salah satu field input, dan semua field lainnya akan terkonversi secara otomatis secara real-time tanpa perlu menekan tombol apa pun.",
        "Kalkulator bilangan ini mendukung bilangan positif dan negatif dengan presisi tinggi menggunakan BigInt, sehingga dapat menangani angka besar tanpa batasan. Fitur tambahan termasuk pengelompokan 4-bit pada bilangan biner untuk memudahkan pembacaan, opsi huruf besar/kecil pada output heksadesimal, serta informasi jumlah digit atau bit dari setiap bilangan yang dimasukkan. Setiap field juga dilengkapi tombol salin untuk menyalin hasil konversi dengan cepat.",
        "Konversi bilangan memiliki banyak kegunaan praktis dalam dunia teknologi: membaca dan menulis alamat IPv4 dan IPv6, memahami representasi data dalam memori komputer, melakukan debugging pada level bit, menyelesaikan soal-soal mata kuliah arsitektur komputer dan jaringan, serta bekerja dengan permission file di sistem Linux (755, 644, dll.) yang menggunakan notasi oktal. Semua proses konversi dilakukan sepenuhnya di browser Anda tanpa mengirim data ke server mana pun, sehingga privasi data Anda tetap terjaga."
    ),
    "Kalkulator Subnetting": (
        "Kalkulator subnetting online untuk menghitung network address, broadcast address, subnet mask, wildcard mask, CIDR notation, dan host range dari sebuah jaringan IP. Alat ini dirancang khusus untuk network engineer, administrator jaringan, mahasiswa teknik informatika, dan profesional IT yang perlu melakukan perhitungan subnetting secara cepat dan akurat. Kalkulator ini mendukung perhitungan IPv4 subnetting dengan berbagai prefix length dari /1 hingga /32.",
        "Cara penggunaannya sangat sederhana: masukkan alamat IP network, pilih prefix awal subnet, lalu tentukan prefix baru yang diinginkan untuk pemotongan subnet. Hasil perhitungan akan menampilkan informasi lengkap termasuk kelas IP (A, B, atau C), subnet mask dalam format desimal, wildcard mask, alamat network dan broadcast, first dan last host yang valid, serta jumlah total host yang tersedia. Kalkulator VLSM ini juga menampilkan tabel lengkap berisi semua subnet hasil pemotongan beserta detail masing-masing.",
        "Fitur unggulan dari network calculator ini adalah kemampuannya menampilkan tabel subnetting lengkap hingga ribuan subnet (dibatasi 4096 subnet untuk performa). Setiap baris tabel menampilkan nomor subnet, alamat network dengan prefix, first host, last host, broadcast address, jumlah host per subnet, dan notasi CIDR. Ini sangat membantu untuk perencanaan jaringan, pembagian IP address dalam organisasi, dan persiapan sertifikasi jaringan seperti CCNA. Semua komputasi dilakukan di sisi klien tanpa koneksi internet."
    ),
    "Hash Generator": (
        "Hash generator online untuk menghasilkan nilai hash dari teks menggunakan berbagai algoritma kriptografi: MD5, SHA-1, SHA-224, SHA-256, SHA-384, SHA-512, SHA3-256, dan SHA3-512. Alat ini sangat berguna bagi developer, security engineer, dan siapa pun yang perlu memverifikasi integritas data, menyimpan password, membuat checksum file, atau bekerja dengan digital signature. Cukup masukkan teks pada kolom input, klik Generate, dan semua varian hash akan ditampilkan sekaligus.",
        "Setiap hasil hash dilengkapi tombol Copy untuk menyalin nilai hash ke clipboard dengan sekali klik. Tabel hasil menampilkan nama algoritma dan nilai hash dalam format heksadesimal yang siap digunakan. Hash generator ini menggunakan library CryptoJS yang terpercaya untuk memastikan akurasi dan kompatibilitas dengan standar industri. Proses hashing dilakukan sepenuhnya di browser menggunakan Web Crypto API, sehingga teks asli Anda tidak pernah dikirim atau disimpan di server mana pun.",
        "Kegunaan hash dalam pengembangan perangkat lunak sangat luas: memverifikasi integritas file yang diunduh dari internet, menyimpan password dengan aman di database (setelah ditambahkan salt), membuat checksum untuk backup data, mendeteksi perubahan file, digital signature, dan berbagai aplikasi kriptografi lainnya. Hash generator ini juga mendukung input teks yang panjang dan menampilkan perbandingan panjang hash antar algoritma. Cocok digunakan kapan saja dan di mana saja langsung dari browser."
    ),
    "Password Generator": (
        "Password generator online untuk membuat kata sandi acak yang kuat dan aman dengan panjang 8 hingga 128 karakter. Alat ini membantu Anda menghasilkan password kompleks yang sulit ditebak dan kebal terhadap serangan brute force. Fitur kustomisasi meliputi pengaturan panjang password, pemilihan jenis karakter (huruf besar, huruf kecil, angka, simbol), serta opsi untuk menghindari karakter ambigu seperti O, 0, I, l, dan 1 yang sering tertukar.",
        "Setiap password yang dihasilkan dilengkapi dengan password strength indicator yang menampilkan tingkat keamanan secara real-time (lemah, sedang, kuat, atau sangat kuat) serta estimasi waktu yang dibutuhkan untuk memecahkan password tersebut. Hasil password bisa langsung disalin dengan tombol Copy. Generator kata sandi ini tidak menyimpan, mengirim, atau mencatat password yang dihasilkan -- semua proses terjadi di browser Anda sehingga privasi tetap terjaga.",
        "Password generator sangat penting untuk menjaga keamanan akun digital Anda. Dengan semakin banyaknya layanan online yang kita gunakan, menggunakan password yang sama untuk semua akun sangat berbahaya. Alat ini membantu Anda membuat password unik dan kuat untuk setiap akun: sosial media, email, internet banking, e-commerce, VPN, dan layanan cloud. Gunakan password minimal 12 karakter dengan kombinasi huruf besar, huruf kecil, angka, dan simbol untuk keamanan optimal. Generator password ini gratis dan tidak terbatas jumlah penggunaannya."
    ),
    "Base64 Encode/Decode": (
        "Base64 encoder dan decoder online untuk mengkonversi teks biasa menjadi encoding Base64 dan sebaliknya. Base64 adalah skema encoding yang mengubah data biner menjadi format teks ASCII yang aman untuk ditransmisikan melalui media yang hanya mendukung teks, seperti email (MIME), URL, dan data JSON. Alat ini sangat penting bagi web developer, backend engineer, dan siapa pun yang bekerja dengan transmisi data antar sistem.",
        "Cara penggunaannya intuitif: tempelkan teks yang ingin di-encode atau di-decode ke dalam kolom input, lalu pilih operasi yang diinginkan. Hasil encoding atau decoding akan ditampilkan secara instan dan bisa langsung disalin ke clipboard. Base64 converter ini mendukung teks dengan berbagai karakter termasuk Unicode, simbol, dan spasi. Cocok untuk mengirim data biner melalui API, menyematkan gambar sebagai data URI di HTML/CSS, atau menyandikan kredensial untuk HTTP Basic Authentication.",
        "Penggunaan umum Base64 encoding meliputi: melampirkan file dalam email (MIME), menyematkan gambar kecil langsung di kode HTML atau CSS (data:image/png;base64,...), menyandikan token autentikasi, merepresentasikan data kriptografi (sertifikat, kunci publik dalam format PEM), dan menyimpan data biner di database yang hanya mendukung teks. Semua proses encoding dan decoding dilakukan sepenuhnya di browser Anda tanpa mengirim data ke server."
    ),
    "UUID/GUID Generator": (
        "UUID (Universally Unique Identifier) atau GUID (Globally Unique Identifier) generator online untuk membuat identifier unik secara instan. Alat ini mendukung pembuatan UUID versi 1 (berbasis waktu dan MAC address), versi 3 (berbasis namespace MD5), versi 4 (acak), dan versi 5 (berbasis namespace SHA-1). UUID banyak digunakan dalam pengembangan perangkat lunak untuk mengidentifikasi entity secara unik tanpa memerlukan koordinasi terpusat.",
        "Generator ini menyediakan beberapa format output: format standar dengan tanda hubung (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx), tanpa tanda hubung, huruf besar/kecil, dan format array untuk berbagai bahasa pemrograman. Cukup pilih versi UUID yang diinginkan, atur jumlah yang akan digenerate (hingga 10 sekaligus), dan klik tombol Generate. Hasil dapat disalin satu per satu atau semua sekaligus dengan tombol Copy All.",
        "UUID versi 4 berbasis angka acak kriptografis adalah yang paling umum digunakan karena sederhana dan cukup unik untuk hampir semua aplikasi praktis. UUID digunakan sebagai primary key di database, ID sesi pengguna, ID pesanan atau transaksi, ID file atau dokumen, ID perangkat dalam sistem IoT, dan identifier untuk resource dalam REST API. Dengan UUID, risiko tabrakan ID sangat kecil sehingga ideal untuk sistem terdistribusi dan aplikasi skala besar."
    ),
    "QR Code Generator": (
        "QR code generator online untuk membuat QR code dari teks, URL, atau data apa pun secara instan. Cukup masukkan teks atau URL, pilih ukuran, level error correction, warna foreground dan background, lalu klik Generate. QR code yang dihasilkan dapat langsung di-download sebagai file PNG dengan resolusi tinggi sesuai ukuran yang dipilih (dari 128px hingga 1024px). QR generator ini berjalan sepenuhnya di sisi klien tanpa mengirim data ke server.",
        "Fitur kustomisasi meliputi pengaturan ukuran QR code (128px hingga 1024px), level error correction (L 7%, M 15%, Q 25%, H 30%), margin, serta warna foreground dan background yang bisa disesuaikan. Level error correction yang lebih tinggi memungkinkan QR code tetap terbaca meskipun sebagian rusak atau tertutup logo. Anda juga bisa me-refresh halaman dengan parameter URL ?t=... untuk prefill teks secara otomatis.",
        "QR code memiliki banyak kegunaan praktis dalam kehidupan sehari-hari: membagikan link website, alamat kontak (vCard), koneksi WiFi, pembayaran digital (QRIS), menu restoran digital, tiket event, undangan pernikahan, dan informasi produk. QR code yang dihasilkan bisa di-scan dengan kamera smartphone atau aplikasi QR reader apa pun. Generator ini gratis, tanpa batasan jumlah generate, dan bisa digunakan untuk keperluan pribadi maupun komersial."
    ),
    "Color Picker": (
        "Color picker online lengkap dengan dukungan format warna HEX, RGB, HSL, dan CMYK. Alat ini membantu desainer grafis, web developer, dan siapa pun yang bekerja dengan warna untuk memilih, mengkonversi, dan mendapatkan kode warna secara presisi. Cukup klik pada color wheel atau masukkan nilai warna pada salah satu format, dan semua format lainnya akan terkonversi secara otomatis secara real-time.",
        "Fitur unggulan color picker ini meliputi: color wheel interaktif dengan 360 derajat hue, slider saturation dan lightness, input numerik presisi untuk setiap format, riwayat warna yang telah dipilih, dan palet warna yang sudah jadi. Setiap warna yang dipilih dapat disalin ke clipboard dalam format yang diinginkan. Mendukung juga pemilihan warna dari layar melalui input color native browser.",
        "Konversi warna antar format sangat penting dalam workflow desain: desainer web menggunakan HEX dan RGB untuk CSS, desainer cetak menggunakan CMYK, dan desainer UI sering bekerja dengan HSL untuk kemudahan readability dan adjustability. Color picker ini juga menampilkan preview warna dalam bentuk swatch besar, kode HEX lengkap dengan hash, nilai RGB desimal, dan persentase CMYK. Cocok digunakan untuk desain website, pembuatan konten visual, ilustrasi digital, dan pengembangan aplikasi."
    ),
    "JSON Formatter": (
        "JSON formatter online untuk memformat, memvalidasi, dan mempercantik data JSON. Alat ini membantu developer memeriksa struktur JSON, menemukan error syntax, dan mengubah JSON mentah menjadi format yang mudah dibaca dengan indentasi yang rapi. Mendukung berbagai mode: format/beautify dengan indentasi 2 atau 4 spasi, minify untuk memperkecil ukuran data, dan validasi untuk mendeteksi syntax error secara akurat.",
        "Cara penggunaan: tempelkan data JSON ke kolom input, pilih mode yang diinginkan (format, minify, atau validasi), dan hasil akan ditampilkan secara instan. Fitur tree view menampilkan hierarki JSON dalam bentuk expandable tree yang memudahkan navigasi data kompleks. Tombol copy tersedia untuk menyalin hasil, dan terdapat juga contoh data JSON untuk percobaan cepat. JSON validator ini mampu mendeteksi berbagai jenis error seperti missing comma, bracket tidak seimbang, dan string tanpa tanda kutip.",
        "JSON (JavaScript Object Notation) adalah format pertukaran data standar yang digunakan secara luas dalam REST API development, konfigurasi aplikasi, penyimpanan data NoSQL, dan komunikasi client-server. JSON formatter sangat penting dalam workflow pengembangan: debugging response API, membaca file konfigurasi, mentransformasi data antar format, dan dokumentasi API. Semua pemrosesan dilakukan di browser tanpa mengirim data ke server."
    ),
    "Regex Tester": (
        "Regex tester online untuk menguji dan memvalidasi regular expression secara real-time. Alat ini membantu developer menulis, menguji, dan menyempurnakan pola regex sebelum digunakan dalam kode. Mendukung berbagai flag seperti global (g), case-insensitive (i), multiline (m), dan single-line (s). Fitur live match highlighting menampilkan hasil pencocokan secara langsung saat Anda mengetik pola regex.",
        "Terdapat tiga mode operasi: match untuk menemukan semua kecocokan pola dalam teks, replace untuk mengganti teks yang cocok dengan string baru, dan split untuk memotong teks berdasarkan pola regex. Regex tester ini juga menampilkan detail setiap match termasuk posisi awal dan akhir dalam teks. Cocok untuk pengujian pola validasi input form, ekstraksi data dari teks tidak terstruktur, parsing log file, dan transformasi teks berbasis pola.",
        "Regular expression adalah alat yang sangat powerful untuk pemrosesan teks. Dengan regex tester ini Anda bisa: memvalidasi format email, nomor telepon, atau URL; mengekstrak data dari file HTML atau log; melakukan search and replace berbasis pola; memisahkan teks berdasarkan delimiter kompleks; dan menguji pola sebelum deploy ke production. Proses pengujian regex dilakukan sepenuhnya di browser, sehingga data teks Anda tetap privat dan aman."
    ),
    "Markdown Previewer": (
        "Markdown previewer online untuk menulis dan melihat hasil rendering markdown secara real-time. Alat ini sangat berguna bagi developer, penulis teknis, content creator, dan siapa pun yang bekerja dengan format markdown untuk dokumentasi, blog post, README file, atau catatan. Tampilan side-by-side menampilkan editor markdown di sisi kiri dan hasil preview HTML yang sudah di-render di sisi kanan.",
        "Markdown editor ini mendukung sintaks markdown standar: heading (H1-H6), bold dan italic, blockquote, list ordered dan unordered, code inline dan code block dengan syntax highlighting, tabel, link, gambar, horizontal rule, dan task list. Preview diperbarui secara otomatis setiap kali Anda mengetik, tanpa perlu menekan tombol refresh. Hasil markdown dapat disalin dalam format HTML jadi atau markdown mentah.",
        "Markdown adalah format markup ringan yang banyak digunakan di GitHub, GitLab, Reddit, Discord, dan berbagai platform dokumentasi. Markdown previewer ini membantu Anda: menulis dokumentasi proyek dengan format yang rapi, menyusun README file untuk repositori GitHub, membuat catatan dengan struktur yang jelas, menulis konten blog dalam format markdown, dan belajar sintaks markdown secara interaktif. Semua rendering dilakukan di browser."
    ),
    "Unit Converter": (
        "Unit converter online lengkap untuk konversi satuan antar berbagai sistem pengukuran. Mendukung kategori: panjang (meter, cm, inch, feet, yard, mile, km), berat (kg, gram, pound, ounce), suhu (Celsius, Fahrenheit, Kelvin), volume (liter, gallon, ml, cup), luas (m², ft², acre, hectare), dan kecepatan (km/jam, mph, knot, m/s). Alat ini berguna bagi pelajar, profesional, traveler, dan siapa pun yang perlu konversi satuan cepat dan akurat.",
        "Cara penggunaan: pilih kategori satuan yang diinginkan, masukkan nilai pada satuan asal, dan hasil konversi akan ditampilkan secara real-time di semua satuan lainnya. Kalkulator unit ini mendukung konversi antar sistem metrik dan imperial, serta menampilkan faktor konversi dan rumus yang digunakan. Setiap hasil dapat disalin ke clipboard dengan sekali klik. Antarmuka yang bersih dan responsif memudahkan penggunaan di perangkat desktop maupun mobile.",
        "Konverter satuan sangat berguna dalam berbagai situasi: memasak dengan resep dari luar negeri (konversi cup ke ml, Fahrenheit ke Celsius), perjalanan ke negara dengan sistem satuan berbeda (mil ke km, pound ke kg), pekerjaan teknis dan engineering (inch ke mm, feet ke meter), belajar fisika dan matematika, serta belanja online internasional. Semua konversi dilakukan di browser tanpa koneksi internet."
    ),
    "Text Case Converter": (
        "Text case converter online untuk mengubah format kapitalisasi teks dengan cepat. Mendukung berbagai format: UPPERCASE (huruf besar semua), lowercase (huruf kecil semua), Title Case (kapital di setiap kata), Sentence case (kapital di awal kalimat), camelCase, PascalCase, snake_case, kebab-case, dan CONSTANT_CASE. Alat ini sangat berguna bagi developer, penulis, content creator, dan editor teks.",
        "Cara penggunaan: tempelkan atau ketik teks pada kolom input, dan hasil konversi untuk semua format akan ditampilkan secara real-time tanpa perlu menekan tombol apa pun. Setiap hasil format dilengkapi dengan tombol Copy untuk menyalin ke clipboard dengan cepat. Anda juga dapat meng-upload file teks atau menjatuhkan (drag & drop) teks langsung ke area input. Case converter ini juga menampilkan jumlah karakter dan kata dari teks asli.",
        "Text case converter sangat membantu dalam berbagai skenario programming: mengkonversi nama variabel antara camelCase (JavaScript) dan snake_case (Python), memformat judul artikel atau heading, memperbaiki teks yang salah kapitalisasi, mempersiapkan data untuk database, dan memformat output untuk berbagai kebutuhan. Alat ini bekerja sepenuhnya offline di browser Anda tanpa mengirim data ke server."
    ),
    "Lorem Ipsum Generator": (
        "Lorem ipsum generator online untuk menghasilkan teks dummy atau placeholder text dengan cepat. Alat ini berguna bagi desainer web, graphic designer, developer, dan content creator yang membutuhkan teks pengisi untuk mockup desain, prototipe website, percetakan, atau preview layout. Anda dapat mengatur jumlah paragraf, kata, atau kalimat yang ingin dihasilkan.",
        "Fitur kustomisasi meliputi: jumlah paragraf (1-50), panjang paragraf (pendek, sedang, panjang), opsi untuk memulai dengan 'Lorem ipsum dolor sit amet...' klasik atau teks acak penuh, serta format output dalam bentuk plain text atau HTML dengan tag paragraph. Hasil teks dapat langsung disalin ke clipboard dengan tombol Copy. Anda juga bisa memilih varian teks seperti standar lorem ipsum, Cicero Latin, atau teks placeholder berbahasa Indonesia.",
        "Teks dummy atau placeholder text sangat penting dalam workflow desain dan pengembangan: mengisi konten sementara pada mockup website sebelum konten asli tersedia, menguji layout dan tipografi, mempresentasikan desain kepada klien, mengisi template percetakan, dan menguji responsive design dengan berbagai panjang teks. Generator ini gratis dan dapat digunakan kapan saja tanpa batasan."
    ),
    "Password Strength Checker": (
        "Password strength checker online untuk menganalisis keamanan kata sandi secara real-time. Alat ini mengevaluasi password berdasarkan berbagai kriteria: panjang karakter, penggunaan huruf besar dan kecil, angka, simbol, dan pola umum. Hasil analisis menampilkan tingkat kekuatan password (sangat lemah, lemah, sedang, kuat, sangat kuat) disertai skor numerik dan saran perbaikan.",
        "Fitur analisis meliputi: deteksi penggunaan karakter berulang, pola keyboard (seperti qwerty atau 12345), kata-kata umum dalam kamus, tanggal lahir, dan informasi personal. Password checker ini juga menampilkan estimasi waktu yang dibutuhkan untuk memecahkan password menggunakan berbagai metode serangan (brute force, dictionary attack, rainbow table). Hasil dapat digunakan sebagai panduan untuk membuat password yang lebih aman.",
        "Keamanan password adalah aspek krusial dalam melindungi akun digital Anda. Dengan password strength checker ini, Anda bisa: mengevaluasi keamanan password sebelum digunakan, mempelajari karakteristik password yang kuat, menghindari kesalahan umum dalam pembuatan password, dan meningkatkan kesadaran akan pentingnya keamanan siber. Semua analisis dilakukan di browser, sehingga password Anda tidak pernah dikirim ke server."
    ),
    "Timer & Stopwatch": (
        "Timer dan stopwatch online dengan fitur lengkap untuk mengukur waktu dengan presisi. Stopwatch mendukung penghitungan waktu maju dengan fitur lap times / split times, sedangkan timer memungkinkan Anda mengatur hitung mundur dari durasi tertentu. Kedua alat ini berguna untuk berbagai kebutuhan: olahraga, memasak, belajar (teknik Pomodoro), presentasi, dan produktivitas sehari-hari.",
        "Fitur stopwatch meliputi: start, stop, dan reset; pencatatan lap times dengan timestamp; tampilan waktu dalam format jam:menit:detik.milidetik; dan daftar riwayat lap yang bisa diekspor. Fitur timer meliputi: pengaturan durasi manual atau preset cepat (1, 3, 5, 10, 15, 30 menit); alarm suara saat waktu habis; dan tampilan visual progress bar. Kedua mode dapat diakses dari tab yang berbeda dalam satu halaman.",
        "Timer dan stopwatch online ini sangat praktis karena tidak perlu menginstal aplikasi tambahan. Gunakan stopwatch untuk: mengukur waktu lari atau olahraga, mencatat waktu pengerjaan tugas, timing presentasi, dan eksperimen laboratorium. Gunakan timer untuk: teknik Pomodoro (25 menit fokus, 5 menit istirahat), memasak, waktu istirahat, dan pengingat aktivitas. Semua fungsi berjalan di browser, bahkan saat berpindah tab."
    ),
    "Screen Recorder": (
        "Screen recorder online untuk merekam layar komputer langsung dari browser tanpa perlu menginstal software tambahan. Alat ini memanfaatkan Web API Screen Capture modern yang didukung oleh browser terkini. Anda dapat merekam seluruh layar, jendela aplikasi tertentu, atau tab browser. Mendukung perekaman dengan audio dari mikrofon untuk menambahkan narasi atau komentar suara.",
        "Cara penggunaan: klik tombol Mulai Rekam, pilih sumber yang ingin direkam (seluruh layar, jendela, atau tab), dan rekaman akan berjalan. Anda bisa menghentikan rekaman kapan saja, dan hasilnya akan langsung dapat diputar kembali atau di-download dalam format WebM. Screen recorder ini juga menampilkan durasi rekaman secara real-time. Kualitas rekaman dapat disesuaikan dengan kebutuhan.",
        "Screen recorder online sangat berguna untuk: membuat video tutorial atau panduan penggunaan software, merekam presentasi atau webinar, demo produk untuk klien, merekam bug report untuk tim developer, membuat konten edukasi, dan mendokumentasikan alur kerja. Semua proses perekaman dan encoding dilakukan di browser Anda. Rekaman tidak dikirim ke server mana pun, sehingga privasi dan keamanan data Anda terjamin."
    ),
    "World Clock": (
        "World clock online untuk menampilkan waktu saat ini dari berbagai zona waktu di seluruh dunia secara real-time. Alat ini menampilkan jam digital untuk kota-kota besar di berbagai benua: Asia (Jakarta, Tokyo, Shanghai, Dubai), Eropa (London, Paris, Berlin, Moskow), Amerika (New York, Los Angeles, Chicago), Australia (Sydney), dan Afrika. Sangat berguna untuk koordinasi meeting internasional, perjalanan, dan komunikasi global.",
        "Setiap zona waktu menampilkan informasi lengkap: nama kota, waktu saat ini (jam:menit:detik), perbedaan waktu relatif terhadap WIB (UTC+7), dan status siang/malam dengan indikator visual. World clock ini juga dilengkapi fitur pencarian kota dan konversi waktu antar zona waktu. Anda bisa menambahkan kota favorit ke daftar yang selalu tampil di atas.",
        "World clock sangat membantu dalam berbagai situasi: merencanakan meeting online dengan tim lintas negara, menelepon keluarga atau relasi di luar negeri pada jam yang tepat, merencanakan perjalanan internasional, mengikuti event global seperti webinar atau conference, dan bekerja sebagai freelancer atau remote worker dengan klien dari berbagai negara. Semua data waktu dihitung berdasarkan waktu sistem komputer Anda."
    ),
    "BMI Calculator": (
        "BMI (Body Mass Index) calculator online untuk menghitung Indeks Massa Tubuh berdasarkan tinggi dan berat badan. BMI adalah metode pengukuran yang digunakan secara luas untuk menilai apakah berat badan seseorang termasuk dalam kategori kurus, normal, overweight (kelebihan berat badan), atau obesitas. Kalkulator BMI ini membantu Anda memantau kesehatan berat badan secara mandiri dan instan.",
        "Cara penggunaan: masukkan tinggi badan dalam sentimeter (cm) dan berat badan dalam kilogram (kg), lalu klik Hitung BMI. Hasil akan menampilkan skor BMI dengan satu angka desimal, kategori berat badan (kekurangan berat badan, normal, kelebihan berat badan, atau obesitas tingkat I/II/III), dan rentang berat badan ideal untuk tinggi Anda. Kalkulator ini juga menampilkan grafik visual posisi BMI Anda dalam skala.",
        "BMI adalah indikator sederhana namun berguna untuk screening kesehatan. Meskipun BMI tidak mengukur persentase lemak tubuh secara langsung, BMI berkorelasi dengan risiko penyakit terkait obesitas seperti diabetes tipe 2, hipertensi, dan penyakit jantung. Kalkulator BMI ini cocok untuk pria dan wanita dewasa usia 18-65 tahun. Penting untuk diingat bahwa BMI hanyalah salah satu indikator dan tidak menggantikan konsultasi dengan tenaga kesehatan profesional."
    ),
    "Typing Speed Test": (
        "Tes kecepatan mengetik online untuk mengukur WPM (Words Per Minute) dan akurasi mengetik Anda. Alat ini menampilkan teks acak berbahasa Indonesia yang harus Anda ketik secepat dan seakurat mungkin dalam durasi yang ditentukan (15, 30, atau 60 detik). Hasil pengukuran meliputi WPM, persentase akurasi, waktu tempuh, dan jumlah karakter benar dan salah.",
        "Cara penggunaan: pilih durasi tes, klik Mulai Tes, dan ketik teks yang ditampilkan di layar. Setiap karakter yang benar akan berwarna hijau, sedangkan yang salah berwarna merah dengan garis bawah. Setelah waktu habis atau teks selesai diketik, hasil akan ditampilkan lengkap dengan skor WPM dan akurasi. Terdapat juga panduan skor: di bawah 30 WPM (lambat), 30-40 (rata-rata), 40-60 (baik), 60-80 (sangat baik), dan 80+ (profesional).",
        "Latihan mengetik secara rutin dapat meningkatkan produktivitas kerja secara signifikan. Typing speed test ini cocok untuk: mengevaluasi kemampuan mengetik saat ini, berlatih meningkatkan kecepatan dan akurasi, mempersiapkan tes kerja yang membutuhkan kemampuan mengetik, mengukur progres latihan dari waktu ke waktu, dan bersenang-senang dengan tantangan mengetik. Tes ini juga bisa digunakan di sekolah atau kursus komputer."
    ),
    "Age Calculator": (
        "Age calculator online untuk menghitung usia secara presisi hingga detail hari. Cukup masukkan tanggal lahir Anda, dan kalkulator usia ini akan menampilkan umur dalam tahun, bulan, hari, jam, menit, dan detik secara real-time. Alat ini sangat berguna untuk menghitung usia tepat untuk berbagai keperluan administrasi, kesehatan, dan perencanaan hidup.",
        "Fitur kalkulator usia ini meliputi: input tanggal lahir dengan date picker yang mudah digunakan, hitungan usia yang diperbarui setiap detik, informasi hari kelahiran (Senin-Minggu), jumlah hari sejak lahir, jumlah minggu sejak lahir, dan ulang tahun berikutnya beserta sisa hari menunggunya. Tampilan hasil yang bersih dan informatif memudahkan pembacaan data usia Anda.",
        "Age calculator memiliki banyak kegunaan praktis: menghitung usia untuk pendaftaran sekolah atau kuliah, verifikasi usia untuk layanan online, perencanaan pensiun, menghitung usia hewan peliharaan, kebutuhan medis (dosis obat berdasarkan usia), dan sekadar ingin tahu usia tepat Anda hingga detik. Kalkulator ini akurat dan memperhitungkan tahun kabisat. Semua perhitungan dilakukan di browser Anda."
    ),
    "Pomodoro Timer": (
        "Pomodoro timer online untuk membantu Anda menerapkan teknik Pomodoro dalam bekerja atau belajar. Teknik Pomodoro adalah metode manajemen waktu yang membagi pekerjaan menjadi interval fokus 25 menit yang dipisahkan oleh istirahat pendek 5 menit. Setelah empat sesi fokus, Anda mengambil istirahat panjang 15-30 menit. Metode ini terbukti meningkatkan produktivitas dan konsentrasi.",
        "Fitur timer ini meliputi: pengaturan durasi fokus default 25 menit (dapat disesuaikan 10-60 menit), istirahat pendek 5 menit, istirahat panjang 15-30 menit, indikator sesi ke berapa, notifikasi suara saat sesi berganti, progress bar visual, dan statistik sesi yang telah diselesaikan hari ini. Timer berjalan meskipun Anda berpindah tab browser.",
        "Teknik Pomodoro membantu mengatasi prokrastinasi, meningkatkan fokus, mencegah kelelahan mental, dan membuat pekerjaan terasa lebih ringan dengan dibagi menjadi sesi-sesi kecil. Pomodoro timer ini cocok untuk: belajar untuk ujian, menulis laporan atau artikel, coding, mengerjakan tugas deadline, dan pekerjaan kreatif. Timer Pomodoro online ini gratis dan bisa langsung digunakan tanpa registrasi."
    ),
    "Countdown Timer": (
        "Countdown timer online untuk menghitung mundur waktu menuju acara spesial atau tenggat waktu tertentu. Alat ini memungkinkan Anda mengatur tanggal dan jam target, lalu menampilkan sisa waktu dalam hari, jam, menit, dan detik yang diperbarui secara real-time. Sangat berguna untuk menghitung mundur menuju liburan, ulang tahun, event, atau deadline proyek.",
        "Fitur countdown meliputi: input tanggal dan jam target, tampilan besar yang mudah dibaca dari jarak jauh, progress bar persentase waktu yang telah berlalu, opsi untuk menambahkan label atau nama acara, dan tombol reset untuk mengatur ulang. Countdown ini dapat ditampilkan dalam mode layar penuh untuk dipajang di monitor atau proyektor selama event.",
        "Countdown timer berguna dalam berbagai situasi: menghitung hari menuju liburan atau perjalanan, momen spesial seperti pernikahan atau kelahiran, peluncuran produk atau website, deadline proyek, event olahraga seperti Olimpiade atau Piala Dunia, Tahun Baru, dan acara penggalangan dana. Anda dapat membuka halaman ini dan membiarkannya berjalan di background browser."
    ),
    "Notes App": (
        "Notes app online untuk menulis dan menyimpan catatan langsung di browser. Aplikasi catatan ini menggunakan localStorage untuk menyimpan catatan Anda secara otomatis, sehingga catatan tetap tersimpan meskipun halaman ditutup atau browser di-refresh. Sangat berguna untuk mencatat ide cepat, to-do list, pengingat, dan informasi penting tanpa perlu login atau registrasi.",
        "Fitur notes app meliputi: membuat catatan baru dengan judul dan konten, mengedit catatan yang ada, menghapus catatan, mencari catatan berdasarkan kata kunci, markdown support untuk format teks, tombol simpan otomatis, jumlah karakter dan kata, serta timestamp kapan catatan terakhir diedit. Antarmuka yang bersih dan minimalis memudahkan fokus pada menulis.",
        "Notes app online ini cocok untuk: mencatat ide kreatif yang muncul tiba-tiba, membuat daftar belanja atau to-do list, menyimpan kutipan inspiratif, menulis jurnal harian, mencatat poin penting dari meeting atau kuliah, dan mengumpulkan referensi. Karena data disimpan di browser, privasi catatan Anda terjaga. Disarankan untuk backup catatan penting secara berkala."
    ),
    "Diff Checker": (
        "Diff checker online untuk membandingkan dua teks dan menampilkan perbedaannya secara detail. Alat ini sangat berguna bagi developer, penulis, editor, dan siapa pun yang perlu membandingkan dua versi teks untuk menemukan perubahan, penambahan, atau penghapusan. Hasil perbandingan ditampilkan dengan kode warna: hijau untuk teks yang ditambahkan dan merah untuk teks yang dihapus.",
        "Cara penggunaan: tempelkan teks versi pertama di kolom kiri dan teks versi kedua di kolom kanan, lalu klik Compare. Hasil diff akan menampilkan perbedaan baris per baris dengan highlighting yang jelas. Anda juga bisa beralih ke mode unified view yang menggabungkan kedua versi dalam satu tampilan. Tombol navigasi memudahkan berpindah antar perbedaan (next/previous diff).",
        "Diff checker memiliki banyak kegunaan: membandingkan versi kode sebelum dan sesudah perubahan, mengecek perubahan dalam file konfigurasi, memvalidasi perubahan konten website, membandingkan output program yang diharapkan dengan aktual, mereview edit teks atau dokumen, dan mendeteksi perubahan dalam data terstruktur. Semua perbandingan dilakukan di browser tanpa mengirim data ke server."
    ),
    "Image to Base64": (
        "Image to Base64 converter online untuk mengubah file gambar menjadi string Base64. Alat ini memungkinkan Anda drag & drop gambar atau memilih file dari komputer, lalu menampilkan hasil encoding Base64 yang siap digunakan sebagai data URI untuk disematkan langsung di HTML, CSS, atau JavaScript. Mendukung berbagai format gambar: PNG, JPG/JPEG, GIF, SVG, WebP, dan BMP.",
        "Cara penggunaan: seret (drag) file gambar ke area yang disediakan atau klik untuk memilih file. Hasil encoding Base64 akan ditampilkan secara instan lengkap dengan data URI prefix (data:image/png;base64,...). Anda bisa menyalin hasil ke clipboard, melihat preview gambar, dan melihat informasi file seperti ukuran asli dan ukuran hasil encoding. Terdapat juga opsi untuk mengatur kualitas kompresi JPEG.",
        "Image to Base64 converter sangat berguna untuk: menyematkan gambar kecil langsung di kode HTML atau CSS untuk mengurangi jumlah HTTP request, membuat email signature dengan logo, menyimpan gambar di database yang hanya mendukung teks, mengirim gambar melalui API dalam format JSON, dan membuat standalone HTML file yang mengandung semua asset dalam satu file. Proses encoding 100% client-side."
    ),
    "JSON ↔ CSV Converter": (
        "JSON to CSV dan CSV to JSON converter online untuk mengkonversi data antara dua format populer secara instan. JSON (JavaScript Object Notation) dan CSV (Comma-Separated Values) adalah dua format data yang banyak digunakan dalam pengembangan aplikasi, analisis data, dan pertukaran informasi antar sistem. Alat ini mendukung array of objects JSON dan berbagai varian CSV.",
        "Fitur konverter ini meliputi: konversi JSON ke CSV dengan header otomatis dari key object, konversi CSV ke JSON array of objects, preview hasil konversi dalam bentuk tabel, opsi delimiter CSV (koma, titik koma, tab), handling nilai null dan nested object, serta tombol copy dan download. Hasil konversi dapat langsung disalin atau di-download sebagai file.",
        "JSON ↔ CSV converter sangat membantu dalam workflow data: mengekspor data API (JSON) ke spreadsheet untuk analisis, mengimpor data dari Excel/Spreadsheet (CSV) ke aplikasi web, migrasi data antar sistem, menyiapkan data untuk machine learning, dan mengolah data untuk reporting. Baik JSON dan CSV adalah format yang ringan, mudah dibaca, dan didukung oleh hampir semua bahasa pemrograman."
    ),
    "SQL Formatter": (
        "SQL formatter online untuk memformat dan mempercantik kode SQL agar lebih mudah dibaca. Alat ini mendukung berbagai dialect SQL: MySQL, PostgreSQL, SQL Server, Oracle, dan SQLite. Cukup tempelkan kode SQL mentah, pilih dialect yang sesuai, dan hasil format yang rapi dengan indentasi yang benar akan ditampilkan secara instan.",
        "Fitur SQL formatter meliputi: format query dengan indentasi otomatis, upper case untuk keyword SQL (SELECT, FROM, WHERE, dll.), lower case untuk identifier, penempatan klausa di baris baru, dan penanganan subquery, JOIN, UNION, dan window functions. Tersedia juga mode minify untuk memperkecil ukuran query. Hasil dapat langsung disalin ke clipboard.",
        "SQL formatter sangat berguna bagi database administrator, backend developer, data analyst, dan siapa pun yang bekerja dengan database relasional. Kode SQL yang diformat dengan baik meningkatkan readability, memudahkan debugging, membantu menemukan error syntax, dan memudahkan kolaborasi tim. Query SQL yang rapi juga lebih mudah dioptimalkan dan didokumentasikan. Pemrosesan dilakukan sepenuhnya di browser tanpa mengirim data ke server."
    ),
    "YAML ↔ JSON Converter": (
        "YAML to JSON dan JSON to YAML converter online untuk mengkonversi data antara dua format konfigurasi yang populer. YAML (YAML Ain't Markup Language) banyak digunakan untuk file konfigurasi karena lebih mudah dibaca manusia, sementara JSON lebih ringan dan banyak digunakan dalam API dan penyimpanan data. Alat ini mendukung konversi dua arah secara instan.",
        "Fitur konverter ini meliputi: konversi YAML ke JSON dengan indentasi yang rapi, konversi JSON ke YAML dengan format yang bersih, validasi syntax untuk kedua format, penanganan berbagai tipe data (string, number, boolean, null, array, object), dukungan untuk YAML multiline string, dan tombol copy untuk menyalin hasil. Preview hasil ditampilkan dalam editor yang nyaman dibaca.",
        "YAML dan JSON converter sangat berguna dalam pengembangan perangkat lunak modern: mengkonversi file konfigurasi Docker Compose (YAML) ke format yang lebih mudah diproses, mengubah file konfigurasi aplikasi (YAML) untuk digunakan dengan API yang membutuhkan JSON, bekerja dengan Kubernetes manifest (YAML), CI/CD pipeline configuration (YAML), dan OpenAPI/Swagger specification yang sering menggunakan kedua format. Semua konversi dilakukan di browser."
    ),
    "URL Encode/Decode": (
        "URL encoder dan decoder online untuk mengkonversi string URL menjadi format yang aman untuk transmisi dan sebaliknya. URL encoding (juga dikenal sebagai percent-encoding) menggantikan karakter khusus dalam URL dengan representasi persen-heksadesimal (%XX) agar dapat ditransmisikan dengan aman melalui internet. Alat ini penting bagi web developer dan siapa pun yang bekerja dengan URL dan parameter query.",
        "Fitur URL encoder/decoder meliputi: encode teks biasa ke format URL-safe, decode URL encoded string kembali ke teks asli, dukungan penuh untuk karakter Unicode dan multibyte, penanganan spasi sebagai %20 (standar) atau + (application/x-www-form-urlencoded), serta mode encode komponen (hanya mengencode bagian tertentu dari URL). Hasil dapat disalin ke clipboard dengan sekali klik.",
        "URL encoding sangat penting dalam pengembangan web: mengirim data melalui URL parameter GET request, membuat query string untuk API calls, mengencode input form yang dikirim via GET method, membuat bookmarklet, mengencode data untuk redirect URL, dan memastikan URL valid saat berisi karakter khusus seperti spasi, &, ?, #, dan =. Semua pemrosesan dilakukan di browser Anda."
    ),
    "IP Calculator": (
        "IP calculator online untuk menghitung informasi subnet dari alamat IP dan CIDR notation. Alat ini membantu network engineer, administrator jaringan, dan mahasiswa IT untuk menghitung network address, broadcast address, subnet mask, wildcard mask, jumlah host, dan range IP yang valid. Mendukung perhitungan untuk semua prefix length dari /0 hingga /32.",
        "Fitur IP calculator ini meliputi: input alamat IP dalam format dotted decimal (192.168.1.0), input prefix length (/24), hasil lengkap meliputi network address, broadcast address, subnet mask, wildcard mask, first dan last host, jumlah total host, dan jumlah usable host. Informasi tambahan seperti kelas IP dan tipe (private/public) juga ditampilkan. Hasil dapat disalin dengan mudah.",
        "IP address calculator sangat berguna untuk: merencanakan skema IP untuk jaringan kantor atau rumah, menghitung kebutuhan subnet untuk segmen jaringan berbeda, troubleshooting konektivitas jaringan, belajar konsep TCP/IP dan subnetting, mempersiapkan sertifikasi jaringan seperti CCNA, dan mengoptimalkan alokasi IP address. Semua perhitungan dilakukan secara client-side di browser."
    ),
    "Character Counter": (
        "Character counter online untuk menganalisis teks secara detail. Alat ini menghitung jumlah karakter (dengan dan tanpa spasi), jumlah kata, jumlah kalimat, jumlah paragraf, jumlah baris, jumlah halaman perkiraan, dan frekuensi kemunculan setiap kata. Sangat berguna bagi penulis, content creator, pelajar, dan profesional yang perlu memenuhi batasan jumlah karakter atau kata.",
        "Fitur analisis meliputi: hitungan real-time saat Anda mengetik atau menempelkan teks, statistik lengkap karakter dan kata, frekuensi kata dalam bentuk daftar atau word cloud, analisis readability (tingkat keterbacaan), durasi membaca dan berbicara, serta deteksi kata unik vs kata berulang. Hasil diperbarui secara instan tanpa perlu menekan tombol.",
        "Character counter sangat praktis untuk: menulis konten dengan batasan karakter tertentu (judul artikel, meta description, SMS, Twitter), mengoptimalkan SEO dengan menghitung panjang konten, mengecek jumlah kata untuk esai atau tugas kuliah, menganalisis frekuensi kata dalam teks, menghitung durasi pidato atau presentasi, dan memastikan teks iklan atau copywriting sesuai ketentuan platform."
    ),
    "Word Counter": (
        "Word counter online untuk menghitung jumlah kata, karakter, kalimat, paragraf, dan statistik teks lainnya secara real-time. Alat ini membantu penulis, editor, mahasiswa, content writer, dan profesional SEO untuk menganalisis konten teks dengan cepat dan akurat. Cukup ketik atau tempelkan teks, dan semua statistik akan diperbarui secara otomatis.",
        "Statistik yang ditampilkan meliputi: jumlah kata total, kata unik, karakter (dengan dan tanpa spasi), jumlah kalimat, jumlah paragraf, rata-rata panjang kata, rata-rata panjang kalimat, kepadatan kata kunci, tingkat keterbacaan (readability score), perkiraan waktu baca, dan perkiraan waktu bicara. Tersedia juga mode analisis frekuensi kata untuk melihat kata apa yang paling sering muncul dalam teks Anda.",
        "Word counter sangat berguna untuk berbagai keperluan: memastikan artikel blog memiliki panjang yang optimal untuk SEO, mengecek jumlah kata esai atau makalah sesuai ketentuan, menganalisis konten iklan dan copywriting, menghitung durasi pidato atau presentasi, mengoptimalkan meta description dan title tag, serta memantau produktivitas menulis harian. Semua analisis dilakukan di browser."
    ),
    "Palindrome Checker": (
        "Palindrome checker online untuk memeriksa apakah sebuah kata, frasa, atau kalimat merupakan palindrome. Palindrome adalah kata, frasa, atau rangkaian karakter yang dibaca sama dari depan maupun dari belakang (misalnya 'radar', 'level', 'kakak', 'kasur ini rusak'). Alat ini mengabaikan spasi, tanda baca, dan kapitalisasi saat melakukan pengecekan.",
        "Fitur palindrome checker meliputi: input teks dengan deteksi real-time, hasil instan 'Palindrome' atau 'Bukan Palindrome', penandaan visual karakter yang cocok/tidak cocok dari kedua ujung, variasi mode pengecekan (case-sensitive/insensitive, ignore/consider spaces and punctuation), riwayat pengecekan, dan contoh kata palindrome dalam bahasa Indonesia dan Inggris. Alat ini juga menampilkan teks yang dibalik (reverse) untuk perbandingan visual.",
        "Palindrome checker berguna untuk: pembelajaran bahasa dan linguistik, teka-teki dan permainan kata, menguji kemampuan pemrograman (soal coding interview), mengecek nama atau username untuk karakter simetris, dan sekadar bersenang-senang dengan kata-kata. Alat ini bekerja sepenuhnya offline di browser Anda."
    ),
    "Anagram Finder": (
        "Anagram finder online untuk memeriksa apakah dua kata atau frasa merupakan anagram satu sama lain. Anagram adalah kata atau frasa yang dibentuk dengan mengatur ulang huruf-huruf dari kata atau frasa lain, menggunakan semua huruf asli tepat satu kali (misalnya 'dengar' dan 'garden', 'listen' dan 'silent'). Alat ini mengabaikan spasi, kapitalisasi, dan tanda baca.",
        "Fitur anagram finder meliputi: input dua teks untuk diperbandingkan, hasil instan 'Anagram' atau 'Bukan Anagram', analisis detail frekuensi huruf dari kedua teks, visualisasi huruf yang cocok dan tidak cocok, mode ignore/consider spaces dan case, riwayat pengecekan, dan contoh anagram bahasa Indonesia dan Inggris. Alat ini juga menampilkan jumlah huruf dari masing-masing teks.",
        "Anagram finder berguna untuk: pembelajaran kosakata dan ejaan, teka-teki dan permainan kata (Scrabble, Word Cookies), menguji kreativitas verbal, membantu menyelesaikan teka-teki silang, dan pengembangan aplikasi game kata. Cocok digunakan oleh pelajar, guru bahasa, dan penggemar permainan kata. Semua pemrosesan dilakukan di browser tanpa perlu koneksi internet."
    ),
    "Reverse Text": (
        "Reverse text online untuk membalikkan urutan karakter, kata, atau baris dalam teks. Alat ini menyediakan berbagai mode reverse yang berguna untuk berbagai keperluan: membalik karakter (olahragA jadi Agarlaho), membalik kata ('saya suka coding' jadi 'coding suka saya'), membalik baris, dan membalik urutan huruf dalam setiap kata. Cukup tempelkan teks dan hasil akan ditampilkan secara instan.",
        "Fitur meliputi: reverse teks per karakter, reverse per kata (membalik urutan kata dalam kalimat), reverse per baris (membalik urutan baris dalam paragraf), reverse per kata secara internal (membalik huruf dalam setiap kata tanpa mengubah urutan kata), dan mode flip text (membalik teks secara vertikal). Setiap mode memiliki tombol copy untuk menyalin hasil dengan cepat.",
        "Reverse text tool berguna untuk: membuat teks unik untuk username atau bio media sosial, menulis teka-teki atau kode sederhana, memeriksa pola simetri dalam teks, belajar tentang struktur kalimat dan kata, menguji readability teks yang dibalik, dan bersenang-senang dengan manipulasi teks. Alat ini bekerja sepenuhnya di browser Anda secara offline."
    ),
    "List Sorter": (
        "List sorter online untuk mengurutkan daftar teks dengan cepat. Alat ini menerima daftar item (satu item per baris) dan mengurutkannya berdasarkan berbagai kriteria: ascending (A-Z), descending (Z-A), ascending numerik, descending numerik, berdasarkan panjang karakter, acak (randomize), dan reverse order. Sangat berguna untuk mengatur data dalam format list atau daftar.",
        "Fitur tambahan meliputi: hapus duplikat (remove duplicates), trim spasi berlebih pada setiap baris, ignore case saat sorting, filter baris yang mengandung kata kunci tertentu, dan opsi untuk mengubah delimiter output (baris baru, koma, titik koma, atau pipe). Hasil pengurutan dapat langsung disalin atau di-download sebagai file teks. Jumlah item yang diurutkan juga ditampilkan.",
        "List sorter sangat membantu dalam berbagai situasi: mengurutkan daftar nama peserta atau siswa, merapikan daftar belanja, mengatur daftar tugas berdasarkan prioritas, mengurutkan kata kunci untuk SEO, merandomize urutan undian atau giveaway, mengurutkan data ekspor dari spreadsheet, dan mempersiapkan data untuk import ke sistem lain. Alat ini cepat, gratis, dan bekerja offline."
    ),
    "Text Repeater": (
        "Text repeater online untuk mengulangi teks sebanyak N kali. Alat ini memungkinkan Anda memasukkan teks, menentukan jumlah pengulangan (1-10.000), memilih delimiter antar pengulangan (spasi, baris baru, koma, tanpa delimiter, atau kustom), dan mendapatkan hasil pengulangan secara instan. Berguna untuk berbagai keperluan testing, pengisian data, dan pembuatan konten.",
        "Fitur text repeater meliputi: input teks bebas, pengaturan jumlah pengulangan dengan slider atau input numerik, pilihan delimiter, opsi untuk menambahkan nomor urut pada setiap pengulangan, preview hasil secara real-time, dan tombol copy untuk menyalin hasil. Jumlah total karakter dan baris hasil juga ditampilkan. Hasil dapat langsung digunakan tanpa perlu menginstal software.",
        "Text repeater berguna untuk: membuat data dummy untuk testing aplikasi, mengisi template berulang, membuat pola teks untuk eksperimen, menghasilkan teks untuk stress testing form atau input field, membuat konten placeholder untuk desain, belajar coding dengan perulangan, dan mengisi spreadsheet dengan data berulang. Semua pemrosesan dilakukan di browser Anda."
    ),
    "Morse Code Converter": (
        "Morse code converter online untuk mengkonversi teks biasa ke kode Morse dan sebaliknya. Morse code adalah sistem representasi huruf, angka, dan tanda baca menggunakan sinyal titik (.) dan garis (-) yang diciptakan oleh Samuel Morse. Alat ini mendukung konversi dua arah dengan dukungan penuh untuk huruf A-Z, angka 0-9, dan tanda baca umum.",
        "Fitur konverter ini meliputi: teks ke Morse (encode) dan Morse ke teks (decode), audio playback kode Morse dengan kecepatan dapat diatur (lambat, sedang, cepat), visual blinking indicator yang menyala sesuai ketukan Morse, tampilan kode Morse dengan format yang rapi (setiap huruf dipisah spasi, setiap kata dipisah garis miring), dan tombol copy untuk menyalin hasil konversi.",
        "Morse code converter berguna untuk: belajar dan berlatih kode Morse, berkomunikasi menggunakan sinyal Morse dalam situasi darurat, teka-teki dan game edukasi, memahami sejarah telekomunikasi, dan eksperimen dengan encoding data. Meskipun sudah jarang digunakan untuk komunikasi sehari-hari, Morse code tetap menjadi keterampilan yang diakui secara internasional dan digunakan dalam radio amatir."
    ),
    "Roman Numeral Converter": (
        "Roman numeral converter online untuk mengkonversi angka antara format desimal (Arab) dan Romawi. Angka Romawi menggunakan kombinasi huruf I, V, X, L, C, D, dan M untuk merepresentasikan nilai numerik. Alat ini mendukung konversi dua arah: dari angka desimal ke Romawi dan dari Romawi ke desimal, dengan rentang nilai yang lengkap.",
        "Fitur konverter ini meliputi: input desimal ke Romawi dengan hasil instan, input Romawi ke desimal dengan validasi aturan penulisan Romawi, dukungan angka Romawi klasik hingga ribuan (M, MM, MMM, dst.), informasi tentang aturan penulisan angka Romawi (subtractive notation: IV = 4, IX = 9, XL = 40, XC = 90, CD = 400, CM = 900), dan tombol copy hasil.",
        "Roman numeral converter berguna untuk: memahami sistem penomoran kuno yang masih digunakan hingga kini, membaca tahun pada film, acara TV, dan bangunan bersejarah, penomoran bab buku, halaman awal (preamble), dan daftar isi, penomoran raja dan paus (Henry VIII, Paus Yohanes Paulus II), dan pembelajaran sejarah matematika. Konverter ini akurat dan mudah digunakan."
    ),
    "Epoch Converter": (
        "Epoch / Unix timestamp converter online untuk mengkonversi antara Unix timestamp dan tanggal-waktu yang dapat dibaca manusia. Unix timestamp adalah jumlah detik yang telah berlalu sejak 1 Januari 1970 pukul 00:00:00 UTC (Epoch Unix). Alat ini mendukung konversi dua arah: timestamp ke tanggal dan tanggal ke timestamp, dengan berbagai format output.",
        "Fitur epoch converter meliputi: konversi timestamp (detik, milidetik, mikrodetik, nanodetik) ke tanggal-waktu dalam berbagai zona waktu (UTC, WIB, WITA, WIT, dan zona waktu global lainnya), konversi tanggal-waktu ke timestamp, format ISO 8601, RFC 2822, dan format kustom, deteksi otomatis apakah input dalam detik atau milidetik, dan tombol copy untuk menyalin hasil. Hasil diperbarui secara real-time.",
        "Unix timestamp converter sangat penting bagi developer: debugging log file yang menggunakan timestamp, mengkonversi waktu database (MySQL TIMESTAMP, PostgreSQL), bekerja dengan API yang mengembalikan timestamp, mengatur jadwal cron job, menghitung selisih waktu antar event, parsing data time series, dan debugging aplikasi yang menggunakan waktu Unix. Konverter ini akurat hingga tingkat milidetik dan nanodetik."
    ),
    "CSS Unit Converter": (
        "CSS unit converter online untuk mengkonversi antara berbagai satuan CSS yang umum digunakan dalam web development. Mendukung konversi antara px, rem, em, vw, vh, %, pt, pc, cm, mm, dan in. Alat ini sangat berguna bagi frontend developer dan web desainer yang perlu memastikan konsistensi ukuran dalam desain responsif.",
        "Cara penggunaan: masukkan nilai pada satuan asal, pilih satuan target, dan hasil konversi akan ditampilkan secara real-time. Untuk konversi yang melibatkan rem dan em, Anda dapat mengatur ukuran font dasar (biasanya 16px untuk rem) dan ukuran font parent (untuk em). Untuk satuan viewport (vw, vh), Anda dapat mengatur ukuran viewport referensi. Hasil konversi dapat langsung disalin.",
        "CSS unit converter sangat membantu dalam workflow pengembangan web: mengkonversi desain dari Figma/Sketch (px) ke unit relatif (rem, em) untuk aksesibilitas, memastikan ukuran font konsisten di seluruh halaman, menghitung ukuran elemen responsif berbasis viewport, mengkonversi satuan cetak (pt, cm) ke satuan layar (px), dan mengoptimalkan CSS untuk berbagai ukuran layar. Semua perhitungan dilakukan di browser."
    ),
    "Date Duration Calculator": (
        "Date duration calculator online untuk menghitung selisih atau durasi antara dua tanggal. Alat ini dapat menghitung jumlah hari, minggu, bulan, dan tahun antara dua tanggal yang dipilih. Sangat berguna untuk perencanaan proyek, menghitung usia, menentukan tenggat waktu, dan berbagai keperluan administratif yang melibatkan perhitungan tanggal.",
        "Fitur kalkulator tanggal ini meliputi: date picker untuk memilih tanggal mulai dan tanggal akhir, perhitungan durasi dalam hari, minggu, bulan, dan tahun, informasi hari dalam seminggu untuk setiap tanggal, jumlah hari kerja (weekday) vs akhir pekan (weekend), daftar hari libur opsional, dan opsi untuk menambahkan atau mengurangi hari dari tanggal tertentu. Hasil perhitungan akurat termasuk tahun kabisat.",
        "Date calculator berguna dalam berbagai situasi: menghitung umur seseorang secara presisi, merencanakan jadwal proyek dan milestone, menentukan tanggal jatuh tempo atau deadline, menghitung masa kerja atau kontrak, merencanakan liburan atau perjalanan, menghitung sisa hari menuju acara tertentu, dan keperluan administrasi penggajian atau tagihan. Kalkulator ini mudah digunakan dan akurat."
    ),
    "HTTP Status Codes": (
        "HTTP status codes reference online yang menampilkan daftar lengkap kode status HTTP beserta penjelasan dan artinya. HTTP status code adalah respons standar server web yang menunjukkan hasil dari permintaan (request) yang dilakukan browser atau klien. Kode ini dikelompokkan dalam lima kategori: 1xx (Informational), 2xx (Success), 3xx (Redirection), 4xx (Client Error), dan 5xx (Server Error).",
        "Database referensi ini mencakup semua kode standar dari 100 hingga 511, termasuk yang jarang digunakan seperti 103 (Early Hints), 418 (I'm a Teapot), 426 (Upgrade Required), 451 (Unavailable For Legal Reasons), dan 511 (Network Authentication Required). Setiap kode dilengkapi dengan penjelasan singkat, kategori, dan contoh penggunaan. Anda dapat mencari kode berdasarkan angka atau nama.",
        "HTTP status codes reference sangat berguna bagi web developer, backend engineer, QA tester, dan siapa pun yang bekerja dengan pengembangan web dan API. Memahami arti setiap kode HTTP membantu: debugging masalah website dan API, mengimplementasikan error handling yang tepat, mengoptimalkan SEO (301 redirect, 404 handling), mengkonfigurasi server, dan berkomunikasi efektif dengan tim backend. Referensi ini lengkap dan mudah diakses."
    ),
    "HTML Preview": (
        "HTML live preview online untuk menulis kode HTML, CSS, dan JavaScript serta melihat hasil rendering secara real-time. Alat ini menampilkan editor kode di sisi kiri dan preview halaman yang sudah di-render di sisi kanan (atau atas-bawah di perangkat mobile). Sangat berguna untuk prototyping cepat, belajar coding, dan menguji cuplikan kode tanpa perlu setup lingkungan development.",
        "Fitur HTML preview meliputi: editor dengan syntax highlighting untuk HTML, CSS, dan JavaScript; live preview yang diperbarui secara otomatis saat Anda mengetik; dukungan untuk eksternal library via CDN (dengan menambahkan tag link atau script di HTML); mode layar penuh untuk preview; dan tombol untuk menyalin atau mendownload kode. Error JavaScript akan ditampilkan di console area.",
        "HTML live preview sangat berguna untuk: belajar HTML, CSS, dan JavaScript secara interaktif, prototyping ide desain dengan cepat, menguji komponen UI sebelum diintegrasikan ke proyek utama, debugging cuplikan kode, membuat demo untuk dibagikan ke rekan tim atau klien, dan mengajar coding dengan demonstrasi langsung. Semua rendering dilakukan di browser tanpa perlu server."
    ),
    "HTML Entity Encoder/Decoder": (
        'HTML entity encoder dan decoder online untuk mengkonversi karakter khusus menjadi HTML entities dan sebaliknya. HTML entities digunakan untuk menampilkan karakter yang memiliki makna khusus dalam HTML (seperti <, >, &) atau karakter yang tidak tersedia di keyboard. Encoding ini memastikan teks ditampilkan dengan benar di browser tanpa mengganggu struktur HTML.',
        "Fitur encoder/decoder ini meliputi: encode teks biasa ke HTML entities (termasuk karakter spesial, Unicode, dan emoji), decode HTML entities kembali ke teks asli, dukungan untuk named entities (&amp;, &lt;, &gt;, &quot;, &apos;) dan numeric entities (&#34;), mode encode semua karakter atau hanya yang berbahaya untuk XSS, dan tombol copy untuk menyalin hasil.",
        "HTML entity converter sangat penting untuk: mencegah Cross-Site Scripting (XSS) dengan mengencode input pengguna, menampilkan kode contoh atau snippet di halaman web tanpa dieksekusi, menulis konten yang mengandung karakter HTML spesial, mengirim data melalui form tanpa merusak markup, dan memastikan kompatibilitas karakter dengan berbagai encoding halaman. Alat ini bekerja sepenuhnya di browser."
    ),
    "HTML Minifier": (
        "HTML minifier online untuk memperkecil ukuran file HTML dengan menghapus karakter yang tidak perlu tanpa mengubah fungsionalitas. Minification menghapus spasi berlebih, komentar, baris kosong, dan whitespace yang hanya berfungsi untuk readability. Hasilnya adalah file HTML yang lebih ringan, sehingga mempercepat waktu muat halaman dan menghemat bandwidth.",
        "Fitur HTML minifier meliputi: input HTML langsung atau upload file, opsi untuk menghapus komentar HTML, menghapus whitespace berlebih, menghapus atribut type default pada script dan style, menghapus trailing slash pada elemen void, dan opsi untuk mempertahankan kondisional IE comments. Hasil minifikasi ditampilkan dengan perbandingan ukuran sebelum dan sesudah serta persentase penghematan.",
        "HTML minifier sangat berguna untuk: mengoptimalkan kecepatan website dengan mengurangi ukuran file, mempersiapkan file HTML untuk production deployment, menghemat bandwidth hosting, meningkatkan skor PageSpeed Insights dan Lighthouse, mengurangi waktu muat halaman untuk pengguna mobile, dan mengoptimalkan halaman landing page atau email template. Minifikasi adalah praktik standar dalam web performance optimization."
    ),
    "Cron Builder": (
        "Cron expression builder online untuk membuat dan memvalidasi ekspresi cron dengan antarmuka visual yang intuitif. Cron adalah job scheduler berbasis waktu di sistem operasi Unix/Linux yang digunakan untuk menjalankan tugas secara otomatis pada jadwal tertentu. Alat ini membantu Anda membangun ekspresi cron tanpa perlu menghafal sintaks rumitnya.",
        "Fitur cron builder meliputi: antarmuka visual dengan dropdown untuk setiap field cron (menit, jam, hari bulan, bulan, hari minggu), pilihan preset umum (setiap jam, setiap hari, setiap minggu, setiap bulan), validasi ekspresi cron secara real-time, penjelasan dalam bahasa Inggris/Indonesia tentang kapan job akan dijalankan, preview 5 jadwal eksekusi berikutnya, dan dukungan untuk sintaks cron standar serta ekstensi seperti @yearly, @monthly, @weekly, @daily, @hourly.",
        "Cron expression builder sangat berguna untuk: system administrator yang mengelola server Linux, developer yang menggunakan cron job untuk task scheduling (backup database, mengirim email, membersihkan cache), DevOps engineer yang bekerja dengan CI/CD pipeline, dan siapa pun yang perlu menjalankan script secara otomatis pada jadwal tertentu. Alat ini menghemat waktu dengan memvisualisasikan ekspresi cron yang kompleks."
    ),
    "Discount Calculator": (
        "Discount calculator online untuk menghitung harga setelah diskon dan jumlah uang yang dihemat. Alat ini membantu Anda dengan cepat mengetahui berapa yang harus dibayar setelah diskon diterapkan, baik diskon tunggal maupun diskon bertingkat (ganda). Sangat berguna saat berbelanja, baik online maupun offline, untuk membandingkan penawaran dan menentukan keputusan pembelian.",
        "Fitur discount calculator meliputi: input harga asli dan persentase diskon, perhitungan jumlah diskon (hemat) dan harga final, dukungan untuk diskon bertingkat (diskon pertama + diskon kedua dari harga setelah diskon pertama), kalkulasi harga setelah pajak (PPN), perbandingan beberapa skenario diskon, riwayat perhitungan, dan tombol copy hasil. Hasil perhitungan ditampilkan secara real-time.",
        "Calculator diskon ini sangat praktis untuk: berbelanja di mall atau marketplace online (Shopee, Tokopedia, Lazada dengan voucher dan cashback), membandingkan penawaran buy 1 get 1 vs diskon persentase, menghitung penghematan saat belanja dalam jumlah besar, merencanakan anggaran belanja, dan membantu pemilik toko menentukan strategi diskon. Kalkulator ini akurat dan gratis digunakan."
    ),
    "Percentage Calculator": (
        "Percentage calculator online untuk berbagai perhitungan persentase. Alat ini mendukung tiga jenis perhitungan utama: berapa X% dari Y (misal: 15% dari 200), berapa persen X dari Y (misal: 30 dari 150 = 20%), dan perubahan persentase dari X ke Y (misal: kenaikan 50 ke 75 = 50%). Berguna untuk keperluan keuangan, akademik, dan bisnis sehari-hari.",
        "Fitur kalkulator persentase meliputi: tiga mode perhitungan dalam satu antarmuka yang mudah dipindah, input angka yang responsif, hasil ditampilkan berserta rumus perhitungannya, riwayat perhitungan, opsi pembulatan desimal, dan tombol copy hasil. Setiap mode memiliki label yang jelas sehingga Anda tidak bingung memilih rumus yang tepat. Hasil diperbarui secara real-time.",
        "Kalkulator persentase sangat berguna dalam kehidupan sehari-hari: menghitung diskon belanja, menentukan nilai ujian atau tugas (skor yang diperoleh dari total), menghitung kenaikan gaji atau inflasi, menganalisis pertumbuhan bisnis atau penjualan, menghitung komisi atau bonus, menentukan proporsi anggaran, dan membandingkan data statistik. Alat ini sederhana, cepat, dan akurat."
    ),
    "Tip Calculator": (
        "Tip calculator online untuk menghitung tip (uang pelayanan) dan membagi tagihan secara adil di antara beberapa orang. Alat ini sangat berguna saat makan di restoran, menggunakan jasa layanan (salon, taksi, hotel), atau situasi lain di mana memberi tip adalah kebiasaan. Cukup masukkan total tagihan, persentase tip, dan jumlah orang yang membagi.",
        "Fitur tip calculator meliputi: input total tagihan, slider atau input persentase tip (10%, 15%, 18%, 20% atau kustom), jumlah orang yang membagi tagihan (1-20), perhitungan real-time yang menampilkan jumlah tip per orang dan total per orang, opsi untuk membulatkan ke atas atau ke bawah, dan tampilan ringkasan yang jelas: tagihan awal, total tip, total keseluruhan, jumlah per orang, dan tip per orang.",
        "Tip calculator membantu Anda: menghindari kebingungan saat membagi tagihan dengan teman atau kolega, memastikan tip yang diberikan sesuai dengan kualitas layanan, merencanakan anggaran makan di luar, dan bersikap adil dalam pembayaran bersama. Kalkulator tip ini mendukung mata uang Rupiah dan bisa digunakan di restoran, kafe, tempat wisata, dan berbagai situasi sosial lainnya. Perhitungan dilakukan real-time di browser."
    ),
    "Mortgage Calculator": (
        "Mortgage calculator online untuk menghitung estimasi cicilan Kredit Pemilikan Rumah (KPR) atau pinjaman properti lainnya. Alat ini membantu calon pembeli rumah merencanakan keuangan dengan menghitung angsuran bulanan berdasarkan jumlah pinjaman, suku bunga, dan tenor pinjaman. Juga menampilkan rincian pembayaran bunga vs pokok selama masa pinjaman.",
        "Fitur kalkulator KPR ini meliputi: input jumlah pinjaman (Rp), suku bunga per tahun (%), dan tenor (tahun), perhitungan angsuran bulanan (fixed), tabel amortisasi lengkap yang menunjukkan rincian pembayaran pokok dan bunga setiap bulan hingga lunas, total bunga yang dibayarkan selama masa pinjaman, total pembayaran keseluruhan, dan grafik visual perbandingan porsi bunga vs pokok dari waktu ke waktu.",
        "Mortgage calculator sangat membantu dalam perencanaan keuangan properti: membandingkan penawaran KPR dari berbagai bank, menentukan tenor yang paling sesuai dengan kemampuan finansial, memahami berapa besar bunga yang akan dibayarkan selama masa pinjaman, merencanakan strategi pelunasan dipercepat, dan menghitung dampak perubahan suku bunga terhadap angsuran bulanan. Kalkulator ini gratis dan informatif."
    ),
    "Savings Calculator": (
        "Savings calculator online untuk menghitung proyeksi tabungan dengan bunga majemuk (compound interest). Alat ini membantu Anda merencanakan keuangan masa depan dengan menghitung berapa banyak uang yang akan terkumpul jika Anda menabung secara rutin dengan bunga berbunga. Sangat berguna untuk perencanaan dana darurat, dana pensiun, atau tujuan keuangan jangka panjang.",
        "Fitur kalkulator tabungan ini meliputi: input setoran awal, setoran bulanan, suku bunga per tahun (%), dan periode tabungan (tahun atau bulan), perhitungan compound interest dengan berbagai frekuensi (harian, bulanan, triwulanan, tahunan), grafik pertumbuhan tabungan dari waktu ke waktu yang membandingkan total setoran vs bunga yang diperoleh, tabel pertahun yang menampilkan detail saldo akhir, total setoran, dan total bunga, serta tombol untuk mendownload data ke CSV.",
        "Kalkulator tabungan membantu Anda: memvisualisasikan kekuatan bunga majemuk dalam menumbuhkan tabungan, menentukan target tabungan bulanan untuk mencapai tujuan keuangan, membandingkan efek frekuensi compounding yang berbeda, merencanakan dana pensiun atau pendidikan anak, memahami pentingnya memulai investasi sedini mungkin, dan membuat keputusan keuangan yang lebih informasi. Semua perhitungan dilakukan di browser."
    ),
    "Compound Interest Calculator": (
        "Compound interest calculator online untuk menghitung pertumbuhan investasi dengan bunga majemuk. Compound interest (bunga berbunga) adalah konsep di mana bunga yang diperoleh ditambahkan kembali ke pokok investasi, sehingga bunga berikutnya dihitung dari jumlah yang lebih besar. Inilah yang disebut sebagai 'keajaiban bunga majemuk' yang sangat powerful untuk investasi jangka panjang.",
        "Fitur kalkulator ini meliputi: input pokok awal, kontribusi periodik (bulanan/tahunan), suku bunga tahunan, periode investasi, dan frekuensi compounding (tahunan, semesteran, triwulanan, bulanan, atau harian). Hasil menampilkan nilai akhir investasi, total kontribusi, total bunga yang diperoleh, grafik pertumbuhan, dan tabel amortisasi tahunan. Terdapat juga perbandingan dengan simple interest (bunga tunggal) untuk menunjukkan keunggulan compound interest.",
        "Compound interest calculator sangat berguna untuk: perencanaan investasi jangka panjang (saham, reksa dana, deposito), perencanaan dana pensiun, simulasi target dana pendidikan anak, memahami efek waktu terhadap pertumbuhan investasi, membandingkan berbagai skenario investasi, dan edukasi keuangan pribadi. Semakin awal Anda mulai berinvestasi, semakin besar efek compound interest yang bisa Anda nikmati."
    ),
    "Calorie Calculator": (
        "Calorie calculator online untuk menghitung BMR (Basal Metabolic Rate) dan TDEE (Total Daily Energy Expenditure). BMR adalah jumlah kalori minimum yang dibutuhkan tubuh untuk menjalankan fungsi vital saat istirahat (bernafas, detak jantung, suhu tubuh). TDEE adalah total kalori yang dibakar per hari termasuk aktivitas fisik. Alat ini membantu Anda merencanakan asupan kalori untuk menurunkan, menambah, atau mempertahankan berat badan.",
        "Cara penggunaan: masukkan jenis kelamin, usia, tinggi badan (cm), berat badan (kg), dan tingkat aktivitas fisik (dari tidak aktif hingga sangat aktif). Kalkulator kalori akan menghitung BMR menggunakan formula Harris-Benedict yang telah direvisi, lalu menghitung TDEE berdasarkan faktor aktivitas. Hasil menampilkan kebutuhan kalori harian untuk mempertahankan berat badan, serta rekomendasi kalori untuk menurunkan atau menambah berat badan secara bertahap.",
        "Calorie calculator sangat membantu dalam perjalanan kesehatan dan kebugaran: menentukan target kalori untuk diet penurunan berat badan yang sehat (defisit 300-500 kalori/hari), merencanakan asupan untuk bulking/membangun otot (surplus kalori), memahami komposisi tubuh dan metabolisme basal, merencanakan program olahraga berdasarkan level aktivitas, dan mencapai tujuan berat badan ideal secara bertahap dan berkelanjutan. Kalkulator ini akurat dan mudah digunakan."
    ),
    "Sleep Cycle Calculator": (
        "Sleep cycle calculator online untuk menghitung waktu tidur optimal berdasarkan siklus tidur manusia. Siklus tidur berlangsung sekitar 90 menit, dan bangun di tengah siklus (bukan di akhir) dapat menyebabkan rasa lelah dan pusing. Alat ini membantu Anda menentukan waktu tidur atau waktu bangun yang ideal agar bangun dalam keadaan segar di akhir siklus tidur.",
        "Fitur sleep calculator meliputi: dua mode perhitungan -- 'Saya mau bangun jam...' (merekomendasikan waktu tidur) dan 'Saya mau tidur jam...' (merekomendasikan waktu bangun), perhitungan berdasarkan siklus tidur 90 menit dengan 5-6 siklus per malam, waktu yang direkomendasikan untuk mulai tidur (termasuk estimasi 14 menit untuk tertidur), dan penjelasan tentang kualitas tidur berdasarkan jumlah siklus yang dicapai.",
        "Sleep cycle calculator membantu Anda: bangun dengan lebih segar dan berenergi, mengurangi efek groggy setelah bangun tidur, mengoptimalkan kualitas istirahat malam, merencanakan jadwal tidur yang konsisten, memahami pentingnya siklus tidur untuk kesehatan, dan meningkatkan produktivitas harian melalui kualitas tidur yang lebih baik. Kalkulator siklus tidur ini didasarkan pada riset ilmiah tentang pola tidur manusia."
    ),
    "Dice Roller": (
        "Dice roller online virtual untuk melempar dadu digital dengan berbagai tipe: D4, D6, D8, D10, D12, D20, dan D100. Alat ini mensimulasikan lemparan dadu acak untuk berbagai keperluan: permainan board game, role-playing games (RPG) seperti Dungeons & Dragons, pengambilan keputusan, dan berbagai permainan yang membutuhkan angka acak. Animasi lemparan dadu yang realistis menambah keseruan.",
        "Fitur dice roller meliputi: pilihan tipe dadu (semua standar RPG), jumlah dadu yang dilempar (1-20), animasi 3D lemparan dadu yang realistis, total nilai lemparan, detail setiap dadu, riwayat lemparan, mode lempar otomatis (rolling), dan sound effect opsional. Hasil lemparan benar-benar acak menggunakan Math.random() yang cukup untuk permainan non-kriptografis.",
        "Dice roller digital sangat berguna untuk: bermain Dungeons & Dragons dan RPG lainnya tanpa perlu membawa dadu fisik, board game yang kehilangan dadu asli, pengambilan keputusan dengan 'dadu takdir', permainan edukasi untuk anak-anak belajar angka dan probabilitas, dan prototyping game yang membutuhkan mekanisme dadu. Roller dadu ini gratis dan siap digunakan kapan saja."
    ),
    "Decision Maker": (
        "Decision maker online untuk membantu Anda mengambil keputusan secara acak. Alat ini menyediakan berbagai mode: acak pilihan (memilih satu dari daftar opsi yang Anda masukkan), lempar koin (heads/tails), dadu digital, dan Magic 8 Ball yang memberikan jawaban klasik. Sangat berguna saat Anda ragu atau bingung menentukan pilihan dalam situasi sehari-hari.",
        "Fitur decision maker meliputi: mode Pilihan Acak -- masukkan daftar pilihan (pisahkan dengan baris baru) dan alat akan memilih satu secara acak; mode Koin -- lempar koin virtual dengan animasi; mode Magic 8 Ball -- ajukan pertanyaan ya/tidak dan dapatkan jawaban acak dari 20 jawaban klasik (Yes, No, Ask again later, dll.); dan riwayat keputusan yang telah dibuat. Tampilan animasi yang menarik membuat penggunaan lebih menyenangkan.",
        "Decision maker online berguna untuk: memutuskan tempat makan atau tujuan liburan, memilih film atau acara TV untuk ditonton, menentukan game yang akan dimainkan, memecah kebuntuan saat tidak bisa memutuskan hal kecil, ice breaking dalam acara kelompok, dan menambah elemen kejutan dalam pengambilan keputusan. Ingatlah untuk tetap menggunakan pertimbangan logis untuk keputusan penting dan serius."
    ),
    "Random Number Generator": (
        "Random number generator online untuk menghasilkan angka acak dalam rentang tertentu. Alat ini memungkinkan Anda menentukan batas bawah dan batas atas, serta jumlah angka acak yang ingin dihasilkan. Berguna untuk berbagai keperluan: undian berhadiah, pemilihan sampel acak, pengacakan urutan, game, dan aplikasi statistik.",
        "Fitur random number generator meliputi: input nilai minimum dan maksimum, jumlah angka yang dihasilkan (1-100), opsi untuk mengizinkan angka duplikat atau tidak, pengurutan hasil (ascending/descending/unsorted), tampilan hasil dalam format daftar atau dipisah koma, tombol generate ulang, dan tombol copy. Animasi atau efek visual saat angka di-generate menambah pengalaman interaktif.",
        "Number randomizer ini sangat praktis untuk: mengadakan giveaway atau undian berhadiah di media sosial, menentukan pemenang lomba atau kontes, memilih nomor lotere atau undian, menghasilkan angka acak untuk eksperimen statistik, membuat variasi data untuk testing, mengacak urutan peserta presentasi, dan memilih soal ujian secara acak. Generator angka acak ini gratis dan mudah digunakan."
    ),
    "Random Color Generator": (
        "Random color generator online untuk menghasilkan warna acak dalam format HEX, RGB, HSL, dan CMYK. Alat ini menampilkan satu atau beberapa warna acak yang dapat Anda kunci (lock) untuk menyimpan warna favorit sambil terus menghasilkan warna baru untuk yang lainnya. Sangat berguna bagi desainer dan developer yang mencari inspirasi palet warna.",
        "Fitur random color generator meliputi: generate satu atau lebih warna acak sekaligus, format warna lengkap (HEX, RGB, HSL, CMYK) untuk setiap warna, tombol lock pada setiap warna untuk mempertahankannya saat generate ulang, tombol copy untuk menyalin kode warna, palet warna yang dapat disimpan sementara, dan opsi untuk membatasi range hue (misal: hanya warna pastel, hanya warna gelap, atau hanya warna cerah).",
        "Random color generator sangat membantu dalam proses kreatif: mencari inspirasi palet warna untuk desain website atau aplikasi, menemukan kombinasi warna yang tidak terpikirkan sebelumnya, menghasilkan variasi warna untuk data visualization, membuat tema warna untuk presentasi, dan eksplorasi warna untuk proyek seni digital. Generator ini memanfaatkan algoritma untuk menghasilkan warna yang estetis dan seimbang."
    ),
    "Gradient Generator": (
        "CSS gradient generator online untuk membuat gradien warna kustom untuk website dan aplikasi. Alat ini memungkinkan Anda membuat linear gradient dan radial gradient dengan antarmuka visual yang intuitif. Anda dapat menambahkan beberapa warna (color stop), mengatur arah gradien, dan melihat preview secara real-time. Kode CSS siap pakai akan dihasilkan secara otomatis.",
        "Fitur gradient generator meliputi: mode linear dan radial gradient, multiple color stops dengan pengaturan posisi, berbagai arah/angle gradien (0-360 derajat, preset: top, bottom, left, right, diagonal), color picker untuk setiap color stop, urutan warna yang bisa di-drag, opsi untuk menambahkan warna intermediate, preview full-size, dan kode CSS yang dapat langsung disalin. Terdapat juga koleksi gradient preset untuk inspirasi cepat.",
        "CSS gradient generator sangat berguna bagi frontend developer dan web desainer: membuat background website yang menarik, mendesain tombol dengan efek gradien, membuat banner dan header yang eye-catching, menghasilkan tekstur visual tanpa gambar (mengurangi HTTP request), dan menambahkan kedalaman pada elemen UI. Gradient yang dihasilkan kompatibel dengan semua browser modern dan siap digunakan di production."
    ),
    "Contrast Checker": (
        "Contrast checker online untuk memeriksa rasio kontras warna antara foreground (teks) dan background sesuai standar WCAG (Web Content Accessibility Guidelines). Alat ini membantu desainer dan developer memastikan bahwa teks pada website dapat dibaca dengan mudah oleh semua pengguna, termasuk mereka yang memiliki gangguan penglihatan atau buta warna.",
        "Fitur contrast checker meliputi: input warna foreground dan background (HEX, RGB, atau color picker), perhitungan rasio kontras secara real-time, indikator lolos/gagal untuk WCAG AA (rasio 4.5:1 untuk teks normal, 3:1 untuk teks besar) dan WCAG AAA (rasio 7:1 untuk teks normal, 4.5:1 untuk teks besar), simulasi buta warna (protanopia, deuteranopia, tritanopia), dan rekomendasi warna alternatif jika kontras tidak memenuhi standar.",
        "Contrast checker sangat penting dalam web accessibility: memastikan website dapat diakses oleh penyandang disabilitas visual, memenuhi persyaratan hukum aksesibilitas di berbagai negara, meningkatkan user experience untuk semua pengguna, mendukung desain inklusif, dan menghindari potensi tuntutan aksesibilitas. Dengan alat ini, Anda dapat mendesain website yang indah sekaligus accessible bagi semua orang."
    ),
    "CSV/TSV Viewer": (
        "CSV viewer online untuk melihat dan menganalisis file CSV (Comma-Separated Values) dan TSV (Tab-Separated Values) langsung di browser. Alat ini mengurai data tabular dan menampilkannya dalam tabel interaktif yang rapi. Sangat berguna bagi data analyst, developer, dan profesional yang bekerja dengan data spreadsheet tanpa perlu menginstal software pengolah data.",
        "Fitur CSV viewer meliputi: upload file CSV/TSV atau paste data langsung, deteksi delimiter otomatis (koma, titik koma, tab, pipe), preview tabel dengan header yang terdeteksi otomatis, sorting kolom (ascending/descending), filter data berdasarkan nilai kolom, pencarian teks dalam seluruh tabel, informasi jumlah baris dan kolom, mode dark/light, dan ekspor data yang sudah difilter. Menangani file dengan ribuan baris tanpa masalah performa.",
        "CSV viewer online sangat praktis untuk: membuka file CSV tanpa Microsoft Excel atau Google Sheets, memeriksa hasil ekspor data dari database atau API, melakukan quick data cleaning dan validasi, menganalisis data log atau data mentah, membandingkan dua file CSV, dan berbagi data tabular dengan rekan tim yang tidak memiliki software spreadsheet. Semua pemrosesan dilakukan di browser, data Anda tetap aman."
    ),
    "RSA Key Generator": (
        "RSA key generator online untuk membuat pasangan kunci RSA (public key dan private key) langsung di browser. RSA adalah algoritma kriptografi asimetris yang banyak digunakan untuk enkripsi data dan digital signature. Alat ini membantu developer dan security professional menghasilkan key pair untuk berbagai keperluan keamanan: SSH, SSL/TLS, OpenPGP, dan aplikasi kriptografi lainnya.",
        "Fitur RSA generator meliputi: pilihan panjang kunci (1024, 2048, 3072, 4096, 8192 bit), format output PEM standar, format output untuk berbagai penggunaan (SSH, OpenSSL, PKCS#8, PKCS#1), preview public key dan private key, tombol copy untuk masing-masing kunci, opsi download sebagai file .pem, dan informasi tentang kekuatan kunci serta estimasi keamanan. Proses generasi menggunakan Web Crypto API untuk keamanan maksimal.",
        "RSA key pair generator sangat penting untuk: mengatur SSH key-based authentication untuk server, membuat SSL certificate signing request (CSR), mengamankan komunikasi email dengan OpenPGP, menandatangani software atau package secara digital, mengenkripsi data sensitif, dan belajar tentang kriptografi asimetris. Semua generasi kunci dilakukan di browser, sehingga private key Anda tidak pernah meninggalkan perangkat Anda."
    ),
    "JWT Decoder": (
        "JWT decoder online untuk mendekode dan memeriksa isi token JWT (JSON Web Token) tanpa perlu validasi signature. JWT adalah standar terbuka (RFC 7519) untuk mentransmisikan informasi antar pihak sebagai objek JSON yang ditandatangani secara digital. Alat ini membantu developer memeriksa header, payload, dan metadata dari JWT token untuk debugging dan pengembangan.",
        "Fitur JWT decoder meliputi: paste JWT token dan decode secara instan, tampilan terpisah untuk header dan payload dalam format JSON yang rapi, informasi claim standar (iss, sub, aud, exp, nbf, iat, jti) dengan penjelasan, konversi timestamp (exp, iat, nbf) ke tanggal yang dapat dibaca, status kadaluwarsa (expired/valid), highlight perbedaan encoding base64, dan tombol copy untuk header dan payload.",
        "JWT decoder sangat berguna dalam pengembangan web dan API: debugging autentikasi dan otorisasi berbasis JWT, memeriksa isi token dari aplikasi atau API yang sedang dikembangkan, memverifikasi klaim dalam token (seperti user ID, role, permission), menginspeksi token yang dikirim oleh client untuk troubleshooting, dan belajar memahami struktur JWT. Alat ini hanya mendekode, tidak memverifikasi signature, sehingga aman digunakan untuk token apa pun."
    ),
    "Slug Generator": (
        "Slug generator online untuk mengubah teks biasa menjadi URL slug yang ramah SEO. Slug adalah bagian dari URL yang mengidentifikasi halaman secara unik dan readable, biasanya menggunakan huruf kecil, angka, dan tanda hubung (misal: 'Cara Membuat Website' menjadi 'cara-membuat-website'). Alat ini penting bagi content writer, SEO specialist, dan web developer.",
        "Fitur slug generator meliputi: input teks dengan konversi real-time, pilihan delimiter (tanda hubung atau underscore), opsi lowercase/uppercase, transliterasi otomatis untuk karakter non-ASCII (seperti mengubah 'é' menjadi 'e' atau 'ñ' menjadi 'n'), penghapusan karakter khusus dan tanda baca, penanganan spasi berlebih, deteksi dan penghapusan duplikat delimiter, dan tombol copy untuk menyalin slug yang dihasilkan. Mendukung berbagai bahasa termasuk Indonesia.",
        "Slug generator sangat berguna untuk: mengoptimalkan URL artikel blog atau halaman website untuk SEO, membuat URL yang mudah dibaca dan diingat pengguna, mengkonversi judul artikel menjadi slug secara konsisten, mempersiapkan URL untuk CMS atau framework web, dan memastikan format URL seragam di seluruh website. URL slug yang baik meningkatkan click-through rate di hasil pencarian dan membantu Google memahami konten halaman."
    ),
    "Emoji Picker": (
        "Emoji picker online untuk mencari, memilih, dan menyalin emoji dengan cepat. Alat ini menampilkan katalog lengkap emoji yang dikelompokkan berdasarkan kategori: Smiley & Emotion, People & Body, Animals & Nature, Food & Drink, Travel & Places, Activities, Objects, Symbols, dan Flags. Setiap emoji ditampilkan dengan nama dan kata kunci untuk memudahkan pencarian.",
        "Fitur emoji picker meliputi: grid emoji dengan tampilan visual yang jelas, fitur pencarian berdasarkan nama atau kata kunci (misal: 'senyum', 'makan', 'bendera'), kategori yang dapat dipilih, jumlah total emoji yang ditampilkan, klik untuk menyalin emoji ke clipboard, riwayat emoji yang baru saja disalin, dan ukuran tampilan yang dapat disesuaikan. Emoji picker ini responsif dan nyaman digunakan di desktop maupun mobile.",
        "Emoji picker online sangat membantu untuk: menambahkan emoji ke postingan media sosial, menulis caption atau deskripsi produk dengan emoji, memperkaya pesan di aplikasi chat, membuat konten marketing yang lebih menarik, mendesain UI aplikasi yang menggunakan emoji, dan mengeksplorasi berbagai emoji yang tersedia di Unicode standar. Alat ini gratis dan selalu diperbarui dengan emoji terbaru."
    ),
    "Base64 Encode/Decode": (
        "Base64 encoder dan decoder online untuk mengkonversi teks biasa menjadi encoding Base64 dan sebaliknya. Base64 adalah skema encoding yang mengubah data biner menjadi format teks ASCII yang aman untuk ditransmisikan melalui media yang hanya mendukung teks, seperti email (MIME), URL, dan data JSON. Alat ini sangat penting bagi web developer, backend engineer, dan siapa pun yang bekerja dengan transmisi data antar sistem.",
        "Cara penggunaannya intuitif: tempelkan teks yang ingin di-encode atau di-decode ke dalam kolom input, lalu pilih operasi yang diinginkan. Hasil encoding atau decoding akan ditampilkan secara instan dan bisa langsung disalin ke clipboard. Base64 converter ini mendukung teks dengan berbagai karakter termasuk Unicode, simbol, dan spasi. Cocok untuk mengirim data biner melalui API, menyematkan gambar sebagai data URI di HTML/CSS, atau menyandikan kredensial untuk HTTP Basic Authentication.",
        "Penggunaan umum Base64 encoding meliputi: melampirkan file dalam email (MIME), menyematkan gambar kecil langsung di kode HTML atau CSS (data:image/png;base64,...), menyandikan token autentikasi, merepresentasikan data kriptografi (sertifikat, kunci publik dalam format PEM), dan menyimpan data biner di database yang hanya mendukung teks. Semua proses encoding dan decoding dilakukan sepenuhnya di browser Anda tanpa mengirim data ke server."
    ),
    "Stopwatch": (
        "Stopwatch online untuk mengukur waktu dengan presisi tinggi. Alat ini menampilkan waktu dalam format jam:menit:detik.milidetik dengan tombol Start, Stop/Lap, dan Reset. Fitur lap times memungkinkan Anda mencatat waktu putaran atau interval tertentu tanpa menghentikan stopwatch utama. Sangat berguna untuk olahraga, eksperimen laboratorium, dan pengukuran waktu presisi.",
        "Fitur stopwatch meliputi: tampilan waktu digital besar yang mudah dibaca, tombol Start/Pause untuk mengontrol waktu, tombol Lap untuk mencatat waktu saat ini tanpa menghentikan stopwatch, daftar lap times dengan timestamp dan selisih antar lap, tombol Reset untuk mengatur ulang, mode fullscreen untuk tampilan yang lebih besar, dan riwayat sesi yang tersimpan. Presisi waktu hingga 10 milidetik untuk pengukuran yang akurat.",
        "Stopwatch online sangat praktis untuk berbagai kebutuhan: mengukur waktu lari, renang, atau latihan olahraga lainnya, timing kecepatan membaca atau mengetik, mengukur durasi eksperimen sains, timing presentasi atau pidato, mengukur waktu siklus proses produksi, dan berbagai keperluan lain yang membutuhkan pengukuran waktu akurat. Tidak perlu aplikasi terpisah -- cukup buka browser dan gunakan."
    ),
    "Timer": (
        "Timer online untuk mengatur hitung mundur dengan durasi yang dapat ditentukan. Alat ini memungkinkan Anda mengatur waktu dari beberapa detik hingga beberapa jam, dan akan memberikan notifikasi atau alarm suara saat waktu habis. Berguna untuk memasak, olahraga, manajemen waktu, presentasi, dan berbagai aktivitas sehari-hari yang membutuhkan pengaturan waktu.",
        "Fitur timer meliputi: input durasi kustom (jam, menit, detik), preset cepat (1, 3, 5, 10, 15, 30, 45, 60 menit), tampilan waktu mundur yang besar dan jelas, progress bar visual, alarm suara saat waktu habis (dengan pilihan suara), tombol pause dan resume, tombol reset, dan notifikasi browser (jika diizinkan). Timer tetap berjalan meskipun Anda berpindah tab atau meminimalkan browser.",
        "Timer online ini sangat serbaguna: timer untuk memasak (merebus telur, memanggang kue, menyeduh teh), timer olahraga (HIIT, plank, rest time), timer presentasi (mengatur durasi bicara), timer belajar (teknik Pomodoro kustom), timer meeting agar tidak overrun, timer istirahat, timer untuk permainan, dan berbagai kebutuhan lainnya. Praktis karena bisa diakses dari perangkat apa pun yang memiliki browser."
    ),
    "Time Converter": (
        "Time converter online untuk mengkonversi waktu antar zona waktu dan format yang berbeda. Alat ini mendukung konversi epoch/Unix timestamp ke tanggal-waktu yang dapat dibaca, konversi antar zona waktu (WIB, WITA, WIT, UTC, dan zona waktu global), serta perhitungan selisih waktu antar lokasi. Sangat berguna untuk koordinasi meeting internasional dan perjalanan lintas zona waktu.",
        "Fitur time converter meliputi: konversi epoch timestamp (detik/milidetik) ke tanggal-waktu dalam format ISO 8601, RFC 2822, dan format lokal; pemilih zona waktu dengan daftar lengkap zona waktu dunia; konversi waktu dari satu zona waktu ke zona waktu lainnya; perbandingan waktu beberapa kota sekaligus; informasi offset UTC dan status Daylight Saving Time (DST); dan tombol copy untuk setiap hasil konversi.",
        "Time converter sangat membantu untuk: menjadwalkan meeting dengan rekan tim di berbagai negara, mengkonversi deadline yang ditentukan dalam zona waktu tertentu, merencanakan perjalanan internasional dan menyesuaikan jet lag, berkomunikasi dengan klien atau partner luar negeri pada jam kerja yang tepat, mengikuti event global (webinar, conference) dari zona waktu berbeda, dan memahami perbedaan waktu global."
    ),
    "Number to Words": (
        "Number to words converter online untuk mengkonversi angka menjadi terbilang dalam bahasa Indonesia. Alat ini mengubah angka numerik (seperti 1.234.567) menjadi representasi kata-kata (satu juta dua ratus tiga puluh empat ribu lima ratus enam puluh tujuh). Sangat berguna untuk membuat kwitansi, faktur, cek, dokumen legal, laporan keuangan, dan berbagai dokumen resmi yang memerlukan penulisan angka dalam bentuk kata.",
        "Fitur konverter ini meliputi: input angka dengan format bebas (bisa menggunakan titik atau koma sebagai pemisah), konversi instan ke terbilang bahasa Indonesia yang baku sesuai EYD, dukungan untuk angka dari 0 hingga triliunan, penanganan angka desimal (koma, misal: 1.250,50 menjadi 'seribu dua ratus lima puluh koma lima puluh'), huruf kapital otomatis di awal kalimat, opsi format 'rupiah' (menambahkan 'rupiah' di belakang), dan tombol copy hasil.",
        "Number to words converter sangat berguna dalam administrasi perkantoran dan bisnis: menulis nominal cek dengan benar, membuat faktur dan invoice, menyusun laporan keuangan, mengisi kwitansi pembayaran, dokumen perjanjian dan kontrak, surat resmi yang mencantumkan nominal uang, dan edukasi matematika untuk anak-anak belajar membaca angka. Konverter ini akurat dan mengikuti kaidah bahasa Indonesia yang benar."
    ),
    "Word Counter (second)": (
        "Word counter online untuk menghitung jumlah kata, karakter, kalimat, paragraf, dan statistik teks lainnya secara real-time. Alat ini membantu penulis, editor, mahasiswa, content writer, dan profesional SEO untuk menganalisis konten teks dengan cepat dan akurat. Cukup ketik atau tempelkan teks, dan semua statistik akan diperbarui secara otomatis.",
        "Statistik yang ditampilkan meliputi: jumlah kata total, kata unik, karakter (dengan dan tanpa spasi), jumlah kalimat, jumlah paragraf, rata-rata panjang kata, rata-rata panjang kalimat, kepadatan kata kunci, tingkat keterbacaan (readability score), perkiraan waktu baca, dan perkiraan waktu bicara. Tersedia juga mode analisis frekuensi kata untuk melihat kata apa yang paling sering muncul dalam teks Anda.",
        "Word counter sangat berguna untuk berbagai keperluan: memastikan artikel blog memiliki panjang yang optimal untuk SEO, mengecek jumlah kata esai atau makalah sesuai ketentuan, menganalisis konten iklan dan copywriting, menghitung durasi pidato atau presentasi, mengoptimalkan meta description dan title tag, serta memantau produktivitas menulis harian. Semua analisis dilakukan di browser."
    ),
}

TITLE_ALIASES = {
    "Base64 Encode / Decode": "Base64 Encode/Decode",
    "Calorie Calculator (BMR/TDEE)": "Calorie Calculator",
    "Color Contrast Checker": "Contrast Checker",
    "Cron Expression Builder": "Cron Builder",
    "CSS Gradient Generator": "Gradient Generator",
    "Epoch / Unix Timestamp Converter": "Epoch Converter",
    "HTML Live Preview": "HTML Preview",
    "JSON Formatter & Validator": "JSON Formatter",
    "JSON \u001d CSV Converter": "JSON \u2194 CSV Converter",
    "Subnetting Calculator": "Kalkulator Subnetting",
    "Text to Slug Generator": "Slug Generator",
    "URL Encode / Decode": "URL Encode/Decode",
    "UUID / GUID Generator": "UUID/GUID Generator",
    "YAML \u001d JSON Converter": "YAML \u2194 JSON Converter",
    "Timer & Stopwatch": "Timer & Stopwatch",
    "Word Counter": "Word Counter (second)",
}


def get_tool_name_from_html(content):
    """Extract tool name from <title> tag."""
    m = re.search(r'<title>(.+?)</title>', content)
    if m:
        return m.group(1).strip()
    return None


def expand_tentang_section(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    tool_name = get_tool_name_from_html(content)
    if not tool_name:
        print(f"  [!] Could not extract title from {filepath}")
        return False
    
    # Find matching expanded content
    lookup = TITLE_ALIASES.get(tool_name, tool_name)
    expanded = EXPANDED.get(lookup)
    if not expanded:
        print(f"  [SKIP] No expanded content for '{tool_name}'")
        return False
    
    # Pattern to find the existing "Tentang" section
    # It's a single-line div pattern
    pattern = r'<div class="mt-4 p-3 rounded" style="background:var\(--surface-soft\);border:1px solid var\(--border\)"><h6 class="fw-bold">Tentang [^<]+</h6>.*?</div>'
    
    replacement = '<div class="mt-4 p-3 rounded" style="background:var(--surface-soft);border:1px solid var(--border)"><h6 class="fw-bold">Tentang ' + tool_name + '</h6>'
    replacement += '<p class="small mb-1" style="line-height:1.6">' + expanded[0] + '</p>'
    replacement += '<p class="small mb-0" style="line-height:1.6">' + expanded[1] + '</p>'
    if len(expanded) > 2:
        replacement += '<p class="small mb-0 mt-2" style="line-height:1.6">' + expanded[2] + '</p>'
    replacement += '</div>'
    
    new_content, count = re.subn(pattern, replacement, content)
    
    if count == 0:
        print(f"  [SKIP] No 'Tentang' section found in {filepath}")
        return False
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    # Count words in expanded section
    total_words = sum(len(p.split()) for p in expanded)
    print(f"  [OK] {tool_name}: ~{total_words} words")
    return True


def main():
    html_files = [f for f in os.listdir(DIR) if f.endswith('.html') and f not in ('index.html', '404.html', 'about.html', 'privacy.html', 'contact.html')]
    html_files.sort()
    
    print(f"Found {len(html_files)} tool pages to process...")
    
    success = 0
    skipped = 0
    for fname in html_files:
        fpath = os.path.join(DIR, fname)
        if expand_tentang_section(fpath):
            success += 1
        else:
            skipped += 1
    
    print(f"\nDone! {success} files updated, {skipped} skipped.")


if __name__ == '__main__':
    main()
